name: Build and Release (Unix/OSX)

on: [push, pull_request]

jobs:
  build:
    name: Build for Linux and Mac
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        build_type: [tiny, regular-asm]
        lua_engine: [LuaJIT, Lua]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      WITH_LUA_ENGINE: ${{ matrix.lua_engine }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure
      run: WITHOUT_AMALG=1 make ${BUILD_TYPE} WITH_LUA_ENGINE=${WITH_LUA_ENGINE}

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Test Extensions and Primitives
      run: luvi test

  deploy-linux:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Fetch
      run: git fetch --unshallow --no-recurse-submodules

    - name: Build
      run: make linux-build && cp luvi-regular-Linux_x86_64 evo-luvi-linux-amd64

    - name: Github Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          evo-luvi-linux-amd64
        draft: false
        prerelease: false

  deploy-macos:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Fetch
      run: git fetch --unshallow --no-recurse-submodules

    - name: Build
      run: make travis-publish && cp luvi-regular-Darwin_x86_64 evo-luvi-darwin-amd64

    - name: Github Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
      # TBD: The source should probably be released separately, not as part of the OSX build workflow?
        files: |
          evo-luvi-source-code-with-dependencies-*.tar.gz
          evo-luvi-darwin-amd64
        draft: false
        prerelease: false
