name: Build and Release (Windows)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build for Windows (x64)
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Make executable
      # Adding in directory listings here to aid with debugging build issues in the future
        run: ./make.bat && dir && cp build/Release/luvi.exe evo-luvi.exe && dir

      # We don't want to deploy a faulty release, so this should fail if the executable is broken
      - name: Verify the build
        run: ./recompile-and-run-all-tests.cmd # Won't actually recompile in this case since there were no changes

      - name: Publish new release
        # Truly "continuous" releases may be overkill here, so better only release tagged versions
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: evo-luvi.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}