name: Release Tagged Versions

on:
  push:
    tags:
      - '*' # Push events to every tag not containing / (that's all of them...)

jobs:
  build:
    name: Build for Windows (x64)
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        run: git clone --recursive https://github.com/evo-lua/evo-luvi.git

      - name: Make executable
      # Adding in directory listings here to aid with debugging build issues in the future
        run: cd evo-luvi && ./make.bat && dir && mv build/Release/luvi.exe ../evo-luvi.exe && cd .. && dir

      # We don't want to deploy a faulty release, so this should fail if the executable is broken
      - name: Verify the build
        run: cd evo-luvi && ./make.bat test

      - name: Publish new release
        uses: softprops/action-gh-release@v1
        with:
          files: evo-luvi.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}